{
 "title": "prometheus-springboot-custom-demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "custom_counter",
   "type": "stat",
   "description": "This is my counter",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "java_custom_counter" }
   ]
  },
  {
   "title": "custom_gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "java_custom_gauge" }
   ]
  },
  {
   "title": "custom_histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    { "expr": "java_custom_histogram_bucket" }
   ]
  }
 ]
}