{
 "title": "prometheus-springboot-actuator-demo",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "Process Open Files",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Open Files"
      },
      {
       "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Max Files"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "repeat": "memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
     "repeat": "memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}