modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      method: GET
      tls_config:
        insecure_skip_verify: false
  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4"
      tls_config:
        insecure_skip_verify: false
